package Projeto3MSIN;

import java.sql.*;
import java.util.ArrayList;

public class DAO_Curso extends DataBase_Connect {

	// Insert
	public void Insert(TO_Curso Curso) {

		PreparedStatement pst;
		String sql = "insert into TabelaCurso(Codigo,NomeCurso,DataInicio,DataFim,Horario,NumeroVagas,Valor,LabSala,Descricao,MatSoftwares,Area) values (?, ?, ?,?,?, ?,?,?,?,?,?)";
		try {
			Connection conn = ConnectionFactory.obtemConexao();
			pst = conn.prepareStatement(sql);

			int autoGeneratedID = Curso.getCodigo();
			pst.setInt(1, autoGeneratedID);
			pst.setString(2, Curso.getNomeCurso());
			pst.setString(3, Curso.getDataInicio());
			pst.setString(4, Curso.getDataFim());
			pst.setString(5, Curso.getHorario());
			pst.setInt(6, Curso.getNumeroVagas());
			pst.setFloat(7, Curso.getValor());
			pst.setInt(8, Curso.getLabSala());
			pst.setString(9, Curso.getDescricao());
			pst.setString(10, Curso.getMatSoftwares());
			pst.setString(11, Curso.getArea());
			pst.executeUpdate();

		} catch (SQLException e) {

			e.printStackTrace();
		}

		closeConnection();
	}

	// Alterar
	public void Update(TO_Curso Curso) {

		PreparedStatement pst;
		String sql = "update TabelaCurso set NomeCurso=?,DataInicio=?,DataFim=?,Horario=?,NumeroVagas=?,Valor=?,LabSala=?,Descricao=?,MatSoftwares=?,Area=? where Codigo= ?";

		try {
			Connection conn = ConnectionFactory.obtemConexao();
			pst = conn.prepareStatement(sql);
			pst.setInt(11, Curso.getCodigo());
			pst.setString(1, Curso.getNomeCurso());
			pst.setString(2, Curso.getDataInicio());
			pst.setString(3, Curso.getDataFim());
			pst.setString(4, Curso.getHorario());
			pst.setInt(5, Curso.getNumeroVagas());
			pst.setFloat(6, Curso.getValor());
			pst.setInt(7, Curso.getLabSala());
			pst.setString(8, Curso.getDescricao());
			pst.setString(9, Curso.getMatSoftwares());
			pst.setString(10, Curso.getArea());
			pst.executeUpdate();
			pst.close();

		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	// Excluir
	public void Excluir(int Codigo) {

		PreparedStatement pst;

		String sql = "delete from TabelaCurso where Codigo=?";

		try {
			Connection conn = ConnectionFactory.obtemConexao();

			pst = conn.prepareStatement(sql);
			pst.setInt(1, Codigo);

			pst.executeUpdate();
			pst.close();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	// Consultar por Codigo
	public TO_Curso Consultar(int Codigo) {

		PreparedStatement pst;
		String sql = "select * from  TabelaCurso where Codigo =?";
		TO_Curso Curso = null;

		try {
			Connection conn = ConnectionFactory.obtemConexao();

			pst = conn.prepareStatement(sql);
			pst.setInt(1, Codigo);
			ResultSet resultSet = pst.executeQuery();
			if (resultSet.next()) {

				Curso = new TO_Curso();
				Curso.setCodigo(resultSet.getInt("Codigo"));
				Curso.setNomeCurso(resultSet.getString("NomeCurso"));
				Curso.setDataInicio(resultSet.getString("DataInicio"));
				Curso.setDataFim(resultSet.getString("DataFim"));
				Curso.setHorario(resultSet.getString("Horario"));
				Curso.setNumeroVagas(resultSet.getInt("NumeroVagas"));
				Curso.setValor(resultSet.getFloat("Valor"));
				Curso.setLabSala(resultSet.getInt("LabSala"));
				Curso.setDescricao(resultSet.getString("Descricao"));
				Curso.setMatSoftwares(resultSet.getString("MatSoftwares"));
				Curso.setArea(resultSet.getString("Area"));

			}
			pst.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return Curso;
	}

	public ArrayList<TO_Curso> consuAll() {

		PreparedStatement pst;
		String sql = "select * from  TabelaCurso";
		ArrayList<TO_Curso> Curso = new ArrayList<TO_Curso>();

		try {
			Connection conn = ConnectionFactory.obtemConexao();
			pst = conn.prepareStatement(sql);

			ResultSet resultSet = pst.executeQuery();
			while (resultSet.next()) {

				TO_Curso TCurso = new TO_Curso();

				TCurso.setCodigo(resultSet.getInt("Codigo"));
				TCurso.setNomeCurso(resultSet.getString("NomeCurso"));
				TCurso.setDataInicio(resultSet.getString("DataInicio"));
				TCurso.setDataFim(resultSet.getString("DataFim"));
				TCurso.setHorario(resultSet.getString("Horario"));
				TCurso.setNumeroVagas(resultSet.getInt("NumeroVagas"));
				TCurso.setValor(resultSet.getFloat("Valor"));
				TCurso.setLabSala(resultSet.getInt("LabSala"));
				TCurso.setDescricao(resultSet.getString("Descricao"));
				TCurso.setMatSoftwares(resultSet.getString("MatSoftwares"));
				TCurso.setArea(resultSet.getString("Area"));
				Curso.add(TCurso);

			}
			pst.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return Curso;
	}

	public ArrayList<TO_Curso> consuAllInfo() {

		PreparedStatement pst;
		String sql = "select * from  TabelaCurso where Area like '%I'";
		ArrayList<TO_Curso> Curso = new ArrayList<TO_Curso>();

		try {
			Connection conn = ConnectionFactory.obtemConexao();

			pst = conn.prepareStatement(sql);

			ResultSet resultSet = pst.executeQuery();
			while (resultSet.next()) {

				TO_Curso TCurso = new TO_Curso();

				TCurso.setCodigo(resultSet.getInt("Codigo"));
				TCurso.setNomeCurso(resultSet.getString("NomeCurso"));
				TCurso.setDataInicio(resultSet.getString("DataInicio"));
				TCurso.setDataFim(resultSet.getString("DataFim"));
				TCurso.setHorario(resultSet.getString("Horario"));
				TCurso.setNumeroVagas(resultSet.getInt("NumeroVagas"));
				TCurso.setValor(resultSet.getFloat("Valor"));
				TCurso.setLabSala(resultSet.getInt("LabSala"));
				TCurso.setDescricao(resultSet.getString("Descricao"));
				TCurso.setMatSoftwares(resultSet.getString("MatSoftwares"));
				TCurso.setArea(resultSet.getString("Area"));
				Curso.add(TCurso);

			}
			pst.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return Curso;
	}

	public ArrayList<TO_Curso> consuAllArtes() {

		PreparedStatement pst;
		String sql = "select * from  TabelaCurso where Area like '%A'";
		ArrayList<TO_Curso> Curso = new ArrayList<TO_Curso>();

		try {
			Connection conn = ConnectionFactory.obtemConexao();

			pst = conn.prepareStatement(sql);

			ResultSet resultSet = pst.executeQuery();
			while (resultSet.next()) {

				TO_Curso TCurso = new TO_Curso();

				TCurso.setCodigo(resultSet.getInt("Codigo"));
				TCurso.setNomeCurso(resultSet.getString("NomeCurso"));
				TCurso.setDataInicio(resultSet.getString("DataInicio"));
				TCurso.setDataFim(resultSet.getString("DataFim"));
				TCurso.setHorario(resultSet.getString("Horario"));
				TCurso.setNumeroVagas(resultSet.getInt("NumeroVagas"));
				TCurso.setValor(resultSet.getFloat("Valor"));
				TCurso.setLabSala(resultSet.getInt("LabSala"));
				TCurso.setDescricao(resultSet.getString("Descricao"));
				TCurso.setMatSoftwares(resultSet.getString("MatSoftwares"));
				TCurso.setArea(resultSet.getString("Area"));
				Curso.add(TCurso);

			}
			pst.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return Curso;
	}

}
