package DAO;

import java.sql.*;
import java.util.ArrayList;

import Factory.ConnectionFactory;
import TO.TO_Aluno;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DAO_Aluno {

	// Insert
	public void Insert(TO_Aluno Aluno) {

		PreparedStatement pst;

		String sql = "insert into TabelaAluno (Ra,Nome,Endereco,Telefone,Email,RG,CPF) values ( ?, ?,?, ?,?,?,?)";
		try {
			Connection conn = ConnectionFactory.obtemConexao();

			pst = conn.prepareStatement(sql);
			int autoGeneratedID = Aluno.getRa();
			pst.setInt(1, autoGeneratedID);
			pst.setString(2, Aluno.getNome());
			pst.setString(3, Aluno.getEndereco());
			pst.setString(4, Aluno.getTelefone());
			pst.setString(5, Aluno.getEmail());
			pst.setString(6, Aluno.getRG());
			pst.setString(7, Aluno.getCPF());
			pst.executeUpdate();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	// Alterar
	public void Update(TO_Aluno Aluno) {

		PreparedStatement pst;

		String sql = "update TabelaAluno set Nome=?,Endereco=?,Telefone=?,Email=?,RG=?,CPF=? where Ra= ?";
		try {
			Connection conn = ConnectionFactory.obtemConexao();
			pst = conn.prepareStatement(sql);

			pst.setInt(7, Aluno.getRa());
			pst.setString(1, Aluno.getNome());
			pst.setString(2, Aluno.getEndereco());
			pst.setString(3, Aluno.getTelefone());
			pst.setString(4, Aluno.getEmail());
			pst.setString(5, Aluno.getRG());
			pst.setString(6, Aluno.getCPF());

			pst.executeUpdate();
			pst.close();

		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	// Excluir
	public void Excluir(int Ra) {

		PreparedStatement pst;

		String sql = "delete from TabelaAluno where Ra=?";
		try {
			Connection conn = ConnectionFactory.obtemConexao();
			pst = conn.prepareStatement(sql);

			pst.setInt(1, Ra);

			pst.executeUpdate();
			pst.close();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	// Consultar por Codigo
	public TO_Aluno  Consultar(int Ra) {

		PreparedStatement pst;

		TO_Aluno  Aluno = null;

		try {
			Connection conn = ConnectionFactory.obtemConexao();

			String sql = "select * from  TabelaAluno where Ra =?";
			pst = conn.prepareStatement(sql);
			pst.setInt(1, Ra);
			ResultSet resultSet = pst.executeQuery();
			if (resultSet.next()) {

				Aluno = new TO_Aluno ();
				Aluno.setRa(resultSet.getInt("Ra"));
				Aluno.setNome(resultSet.getString("Nome"));
				Aluno.setEndereco(resultSet.getString("Endereco"));
				Aluno.setTelefone(resultSet.getString("Telefone"));
				Aluno.setEmail(resultSet.getString("Email"));
				Aluno.setRG(resultSet.getString("RG"));
				Aluno.setCPF(resultSet.getString("CPF"));

			}
			pst.close();
		} catch (SQLException e) {
			e.printStackTrace();

		}
		return Aluno;
	}

}
